### ISSUE TITLE
How to use it modification OperatorMono font ？

### ISSUE THREAD

**Issue by MrZhang123** [powerline/fontpatcher#21]
how to use fontpatcher ? I dowload the fontpatcher project and let the font in fontpatcher folder , i input the command in terminale 
```sh
fontforge -script /Users/imac/Downloads/fontpatcher/setup.py OperatorMono-Book.otf
```
but console error`invalid command name 'OperatorMono-Book.otf'`
how to use fontpatcher ?

**Comment by captain-http** [comment]
Try `fontforge -script scripts/powerline-fontpatcher OperatorMono-Bold.otf`
